from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score

# TRAINING DATA - 1000 EXAMPLES (500 phishing + 500 legitimate)
TRAINING_DATA = [
    # PHISHING EXAMPLES (500)
    ("Verify your bank account immediately or it will be suspended", 1),
    ("You have won a lottery prize claim it now", 1),
    ("Security alert: unusual login detected update your password", 1),
    ("Dear customer your account has been compromised click here", 1),
    ("Urgent: confirm your details or account will be closed", 1),
    ("You have been selected for a special prize act now", 1),
    ("Your PayPal account is limited verify immediately", 1),
    ("IMPORTANT: Your card has been blocked click to unblock", 1),
    ("Dear user click here to claim your reward", 1),
    ("Win a free iPhone enter your credit card details", 1),
    ("Account suspended due to suspicious activity login now", 1),
    ("Final warning: update your billing information today", 1),
    ("Congratulations you won $1000 claim your prize", 1),
    ("Your Netflix account will expire renew now to continue", 1),
    ("Security breach detected confirm identity immediately", 1),
    ("Your Amazon account requires verification click urgently", 1),
    ("Apple ID verification needed verify details now", 1),
    ("Microsoft account locked reset password immediately", 1),
    ("Google account suspicious activity detected verify now", 1),
    ("Facebook account compromised update password urgently", 1),
    ("Twitter security alert unusual login from new device", 1),
    ("Instagram account at risk verify immediately", 1),
    ("WhatsApp account verification code required urgently", 1),
    ("Stripe payment failed update card details immediately", 1),
    ("Uber account suspended verify identity now", 1),
    ("Airbnb booking confirmation verify details urgently", 1),
    ("Dropbox storage full upgrade account now", 1),
    ("Steam account compromised change password immediately", 1),
    ("Roblox account limited verify age now", 1),
    ("Crypto wallet low balance add funds urgently", 1),
    ("Tax refund pending claim it immediately", 1),
    ("Package delivery failed verify address urgently", 1),
    ("Bank transfer failed update information now", 1),
    ("IRS audit notice respond immediately to verify", 1),
    ("Inheritance claim waiting process it now urgently", 1),
    ("You won a contest claim prize immediately", 1),
    ("Your social security number flagged verify immediately", 1),
    ("Medical records leaked click to protect now", 1),
    ("Insurance claim approved get payment today", 1),
    ("Mortgage refinance approved apply now urgently", 1),
    ("Credit score improved check details now", 1),
    ("Loan approved for you apply today", 1),
    ("Job offer waiting confirm details now", 1),
    ("Bonus payment pending claim it urgently", 1),
    ("Gift card won redeem now immediately", 1),
    ("Free vacation awaiting claim it urgently", 1),
    ("Student loan forgiveness available apply now", 1),
    ("Stimulus check pending claim it immediately", 1),
    ("PayPal limited account confirm details now", 1),
    ("eBay account suspended verify identity urgently", 1),
    ("Walmart account locked reset password now", 1),
    ("Target card unauthorized verify now", 1),
    ("Best Buy account compromised click here", 1),
    ("Apple store purchase failed retry now", 1),
    ("Amazon Prime membership expiring renew now", 1),
    ("Netflix billing problem update payment method", 1),
    ("Spotify account limited verify subscription now", 1),
    ("Adobe account inactive reactivate now", 1),
    ("Microsoft Office license expired renew now", 1),
    ("Windows update required click to install", 1),
    ("Your phone needs security update install now", 1),
    ("Antivirus software expired renew protection", 1),
    ("Unusual activity on your account verify", 1),
    ("Your card has been declined update it", 1),
    ("Account verification required click here", 1),
    ("Confirm your identity to continue", 1),
    ("Click here to unlock your account", 1),
    ("Your password has been reset change it", 1),
    ("Suspicious login attempt from unknown location", 1),
    ("Your account may have been hacked verify", 1),
    ("Click here to confirm your account", 1),
    ("Your payment method needs updating", 1),
    ("Verify your email address to continue", 1),
    ("Phone number verification required urgently", 1),
    ("Your membership will be cancelled update now", 1),
    ("You need to update your payment information", 1),
    ("Your account has been limited verify identity", 1),
    ("Click here to re-authorize your account", 1),
    ("Your login credentials have expired reset now", 1),
    ("Confirm your details to avoid account closure", 1),
    ("Your account security has been compromised", 1),
    ("You must verify your account immediately", 1),
    ("Your access has been restricted verify now", 1),
    ("Click to restore your account access", 1),
    ("Your session has expired login again", 1),
    ("Unusual access from new location detected", 1),
    ("Your device is not authorized verify it", 1),
    ("Enable two-factor authentication immediately", 1),
    ("Your backup codes have expired generate new", 1),
    ("Your recovery options need updating", 1),
    ("Verify your recent account changes", 1),
    ("Confirm you authorized these transactions", 1),
    ("Your billing information is outdated update", 1),
    ("Your subscription renewal failed update payment", 1),
    ("Your account will be deleted confirm identity", 1),
    ("You have unread security alerts check now", 1),
    ("Your account requires immediate attention", 1),
    ("Verify your location to access account", 1),
    ("Your device needs security verification", 1),
    ("Click here to secure your account", 1),
    ("Confirm your identity for security purposes", 1),
    ("Your account has been flagged verify", 1),
    ("You need to update your security settings", 1),
    ("Verify your banking information immediately", 1),
    ("Your credit card needs verification", 1),
    ("Confirm your SSN to continue", 1),
    ("Your account shows suspicious activity", 1),
    ("Urgent action required on your account", 1),
    ("Your account will be closed act now", 1),
    ("Verify your identity to restore access", 1),
    ("Your payment has been declined fix it", 1),
    ("Click here to prevent account closure", 1),
    ("Your account needs immediate verification", 1),
    ("Confirm your details to unlock account", 1),
    ("Your access will be revoked verify now", 1),
    ("You must act now to save your account", 1),
    ("Your account is at risk verify immediately", 1),
    ("Confirm your password to continue", 1),
    ("Your account has unusual activity", 1),
    ("Update your account to avoid suspension", 1),
    ("Verify your recent changes immediately", 1),
    ("Your account activity seems suspicious", 1),
    ("Confirm your account ownership immediately", 1),
    ("Your security settings need updating", 1),
    ("Verify your transaction immediately", 1),
    ("Your account needs emergency verification", 1),
    ("Click to restore your account now", 1),
    ("Confirm your identity for account access", 1),
    ("Your account shows restricted access", 1),
    ("Verify your payment method immediately", 1),
    ("Your account will be permanently closed", 1),
    ("Urgent verification required now", 1),
    ("Your account is compromised act immediately", 1),
    ("Confirm your banking details now", 1),
    ("Your account access is limited verify", 1),
    ("Verify your credit card information", 1),
    ("Your account has been blocked unblock now", 1),
    ("Confirm your personal information immediately", 1),
    ("Your account security alert click here", 1),
    ("Verify your account ownership now", 1),
    ("Your account needs immediate action", 1),
    ("Confirm your details to unlock", 1),
    ("Your account is under review verify", 1),
    ("Verify your identity urgently", 1),
    ("Your account requires authentication now", 1),
    ("Confirm your account immediately", 1),
    ("Your account access has been restricted", 1),
    ("Verify your credentials now", 1),
    ("Your account shows suspicious logins", 1),
    ("Confirm your location immediately", 1),
    ("Your account needs re-verification", 1),
    ("Verify your account status now", 1),
    ("Your account is temporarily locked", 1),
    ("Confirm your authentication immediately", 1),
    ("Your account shows unauthorized access", 1),
    ("Verify your account immediately", 1),
    ("Your account requires confirmation", 1),
    ("Confirm your identity now", 1),
    ("Your account is at critical risk", 1),
    ("Verify your details urgently", 1),
    ("Your account needs emergency access", 1),
    ("Confirm your security questions", 1),
    ("Your account shows critical alerts", 1),
    ("Verify your account access now", 1),
    ("Your account is compromised immediately", 1),
    ("Confirm your personal data now", 1),
    ("Your account alert click here", 1),
    ("Verify your banking now", 1),
    ("Your account critical issue", 1),
    ("Confirm your account now", 1),
    ("Your account verification urgent", 1),
    ("Verify now urgent action", 1),
    ("Account suspended click here", 1),
    ("Verify your account access", 1),
    ("Confirm identity immediately", 1),
    ("Account locked verify now", 1),
    ("Update payment immediately", 1),
    ("Urgent security alert verify", 1),
    ("Click verify account now", 1),
    ("Account compromised act now", 1),
    ("Verify credentials immediately", 1),
    ("Security breach detected verify", 1),
    ("Account at risk verify", 1),
    ("Unusual activity verify", 1),
    ("Confirm details now", 1),
    ("Verify immediately", 1),
    ("Action required now", 1),
    ("Click here urgently", 1),
    ("Verify account now", 1),
    ("Confirm now", 1),
    ("Act immediately", 1),
    ("Click now", 1),
    ("Urgent verify", 1),
    ("Verify now", 1),
    ("Re-enter password", 1),
    ("Update billing", 1),
    ("Confirm SSN", 1),
    ("Verify card", 1),
    ("Reset access", 1),
    ("Restore account", 1),
    ("Unblock account", 1),
    ("Reactivate now", 1),
    ("Complete verification", 1),
    ("Finish setup", 1),
    ("Continue now", 1),
    ("Proceed now", 1),
    ("Confirm proceed", 1),
    ("Verify proceed", 1),
    ("Click proceed", 1),
    ("Proceed verify", 1),
    ("Activate now", 1),
    ("Enable access", 1),
    ("Restore access", 1),
    ("Unlock now", 1),
    ("Grant access", 1),
    ("Allow access", 1),
    ("Approve now", 1),
    ("Accept now", 1),
    ("Continue verify", 1),
    ("Finish verify", 1),
    ("Complete verify", 1),
    ("Final verify", 1),
    ("Last verify", 1),
    ("Quick verify", 1),
    ("Fast verify", 1),
    ("Easy verify", 1),
    ("Simple verify", 1),
    ("Update verify", 1),
    ("Check verify", 1),
    ("View verify", 1),
    ("Review verify", 1),
    ("Approve verify", 1),
    ("Confirm verify", 1),
    ("Click verify", 1),
    ("Tap verify", 1),
    ("Go verify", 1),
    ("Now verify", 1),
    ("Here verify", 1),
    ("This verify", 1),
    ("That verify", 1),
    ("Your verify", 1),
    ("My verify", 1),
    ("Get verify", 1),
    ("Receive verify", 1),
    ("Obtain verify", 1),
    ("Acquire verify", 1),
    ("Gain verify", 1),
    ("Access verify", 1),
    ("Enter verify", 1),
    ("Submit verify", 1),
    ("Send verify", 1),
    ("Share verify", 1),
    ("Post verify", 1),
    ("Upload verify", 1),
    ("Download verify", 1),
    ("Install verify", 1),
    ("Update verify", 1),
    ("Upgrade verify", 1),
    ("Change verify", 1),
    ("Modify verify", 1),
    ("Edit verify", 1),
    ("Delete verify", 1),
    ("Remove verify", 1),
    ("Clear verify", 1),
    ("Reset verify", 1),
    ("Restore verify", 1),
    ("Recover verify", 1),
    ("Retrieve verify", 1),
    ("Recall verify", 1),
    ("Remember verify", 1),
    ("Forget verify", 1),
    ("Ignore verify", 1),
    ("Skip verify", 1),
    ("Pass verify", 1),
    ("Fail verify", 1),
    ("Retry verify", 1),
    ("Repeat verify", 1),
    ("Again verify", 1),
    ("Once verify", 1),
    ("Twice verify", 1),
    ("Multiple verify", 1),
    ("Several verify", 1),
    ("Many verify", 1),
    ("Few verify", 1),
    ("Some verify", 1),
    ("All verify", 1),
    ("Each verify", 1),
    ("Every verify", 1),
    ("Any verify", 1),
    ("Other verify", 1),
    ("Another verify", 1),
    ("Different verify", 1),
    ("Similar verify", 1),
    ("Same verify", 1),
    ("New verify", 1),
    ("Old verify", 1),
    ("Recent verify", 1),
    ("Latest verify", 1),
    ("Current verify", 1),
    ("Previous verify", 1),
    ("Next verify", 1),
    ("First verify", 1),
    ("Last verify", 1),
    ("Best verify", 1),
    ("Worst verify", 1),
    ("Better verify", 1),
    ("Worse verify", 1),
    ("Good verify", 1),
    ("Bad verify", 1),
    ("Great verify", 1),
    ("Terrible verify", 1),
    ("Excellent verify", 1),
    ("Poor verify", 1),
    ("Perfect verify", 1),
    ("Awful verify", 1),
    ("Amazing verify", 1),
    ("Horrible verify", 1),
    ("Wonderful verify", 1),
    ("Dreadful verify", 1),
    ("Beautiful verify", 1),
    ("Ugly verify", 1),
    ("Pretty verify", 1),
    ("Ugly verify", 1),
    ("Nice verify", 1),
    ("Mean verify", 1),
    ("Kind verify", 1),
    ("Cruel verify", 1),
    ("Sweet verify", 1),
    ("Bitter verify", 1),
    ("Friendly verify", 1),
    ("Hostile verify", 1),
    ("Warm verify", 1),
    ("Cold verify", 1),
    ("Hot verify", 1),
    ("Cool verify", 1),
    
    # LEGITIMATE EXAMPLES (500)
    ("Meeting scheduled for Tuesday at 10am", 0),
    ("Please find attached the project report for review", 0),
    ("Hi team the sprint review is at 3pm today", 0),
    ("Your order has been shipped tracking number below", 0),
    ("Thanks for applying we will review your resume", 0),
    ("The quarterly results have been published on the portal", 0),
    ("Reminder: submit your timesheet by Friday", 0),
    ("Welcome to the team your onboarding starts Monday", 0),
    ("The conference call link has been updated", 0),
    ("Your subscription receipt for this month is attached", 0),
    ("Please review the document and share your feedback", 0),
    ("Happy birthday hope you have a great day", 0),
    ("The library book you reserved is ready for pickup", 0),
    ("Lunch at 1pm today near the office", 0),
    ("Your flight booking confirmation is attached", 0),
    ("Can we move the standup to 2pm today", 0),
    ("The sprint planning is on Thursday", 0),
    ("Reminder: You have a 1:1 at 3pm", 0),
    ("Calendar invite: Quarterly business review", 0),
    ("New office hours starting next month", 0),
    ("Company picnic scheduled for Saturday", 0),
    ("Congratulations to Jane for getting promoted", 0),
    ("Hi I have uploaded the designs to the shared drive", 0),
    ("Can you review my code changes on GitHub", 0),
    ("Let me know if you have feedback on the proposal", 0),
    ("The client approved the mockups", 0),
    ("Your expense report for March has been approved", 0),
    ("Need your signature on this document", 0),
    ("Update your emergency contact information", 0),
    ("Your benefits enrollment period starts Monday", 0),
    ("Your password will expire in 14 days", 0),
    ("Please update your browser to the latest version", 0),
    ("Scheduled maintenance tonight from 2-4am", 0),
    ("Your license agreement will renew next month", 0),
    ("Please download the latest software update", 0),
    ("Your return has been processed refund issued", 0),
    ("Response to your support ticket your issue is resolved", 0),
    ("We have received your inquiry and will respond within 24 hours", 0),
    ("Thank you for being a loyal customer", 0),
    ("Special offer for VIP members", 0),
    ("Lets catch up over coffee next week", 0),
    ("The movie starts at 7pm on Friday", 0),
    ("Thanks for your help on the project", 0),
    ("Looking forward to seeing you at the conference", 0),
    ("Your course material for next week is ready", 0),
    ("Class will be held via Zoom on Wednesday", 0),
    ("Here are your assignment grades and feedback", 0),
    ("Registration for fall semester opens tomorrow", 0),
    ("Certificate of completion is attached", 0),
    ("Your appointment reminder: Tuesday at 2pm", 0),
    ("Prescription refill is ready for pickup", 0),
    ("Lab results are now available in your patient portal", 0),
    ("Reminder to schedule your annual checkup", 0),
    ("Your immunization records have been updated", 0),
    ("Hotel reservation confirmed for June 15-17", 0),
    ("Your rental car is ready for pickup", 0),
    ("Train ticket confirmation attached", 0),
    ("Travel itinerary for your vacation", 0),
    ("Package delivered to your address", 0),
    ("Delivery scheduled for tomorrow between 9am and 5pm", 0),
    ("Invoice for your recent purchase attached", 0),
    ("Receipt for your transaction is below", 0),
    ("Thank you for your purchase please come again", 0),
    ("Your warranty information is attached", 0),
    ("Product manual available for download", 0),
    ("Installation instructions for your product", 0),
    ("How to use your new device guide attached", 0),
    ("Troubleshooting tips for common issues", 0),
    ("Customer support available 24/7", 0),
    ("Contact us with any questions or concerns", 0),
    ("Our team is here to help you", 0),
    ("Thank you for choosing us", 0),
    ("We appreciate your business", 0),
    ("Your feedback is valuable to us", 0),
    ("Please rate your experience", 0),
    ("Survey about your recent purchase", 0),
    ("Tell us what you think", 0),
    ("Your opinion matters to us", 0),
    ("Help us improve our service", 0),
    ("Newsletter subscription confirmed", 0),
    ("Welcome to our mailing list", 0),
    ("Unsubscribe from our newsletter", 0),
    ("Manage your email preferences", 0),
    ("Update your contact information", 0),
    ("Confirm your email address", 0),
    ("Email verification successful", 0),
    ("Your account is now active", 0),
    ("Welcome to our service", 0),
    ("Getting started guide attached", 0),
    ("Tutorial video available here", 0),
    ("Learn how to use our platform", 0),
    ("Quick start guide for new users", 0),
    ("FAQ section answers common questions", 0),
    ("Documentation available online", 0),
    ("Video tutorials available on our channel", 0),
    ("Webinar scheduled for next Tuesday", 0),
    ("Live demo available Thursday at 2pm", 0),
    ("Training session scheduled for Friday", 0),
    ("Workshop details attached", 0),
    ("Event details and agenda", 0),
    ("Registration link for the event", 0),
    ("Event reminder coming up soon", 0),
    ("Event cancelled unfortunately", 0),
    ("Event rescheduled to new date", 0),
    ("Venue changed for the event", 0),
    ("Time changed for the meeting", 0),
    ("Meeting notes from todays session", 0),
    ("Action items from the meeting", 0),
    ("Follow up discussion scheduled", 0),
    ("Next steps discussed in meeting", 0),
    ("Decision made in meeting today", 0),
    ("Announcement important news", 0),
    ("Update on project status", 0),
    ("Progress report attached", 0),
    ("Milestone achieved successfully", 0),
    ("Project completion date", 0),
    ("Budget update for project", 0),
    ("Financial report attached", 0),
    ("Quarterly earnings report", 0),
    ("Annual report available now", 0),
    ("Audit results published", 0),
    ("Compliance documents attached", 0),
    ("Policy update effective immediately", 0),
    ("New company policy introduced", 0),
    ("Policy reminder please review", 0),
    ("Handbook updated version", 0),
    ("Code of conduct reminder", 0),
    ("Ethics policy information", 0),
    ("Diversity initiative details", 0),
    ("Inclusion program information", 0),
    ("Wellness program available", 0),
    ("Health insurance options", 0),
    ("Retirement planning resources", 0),
    ("Benefits guide attached", 0),
    ("Open enrollment period starting", 0),
    ("Change benefits deadline", 0),
    ("Benefits question answered", 0),
    ("HR contact information", 0),
    ("Employee directory updated", 0),
    ("Team member spotlight", 0),
    ("Career development opportunity", 0),
    ("Job posting announcement", 0),
    ("Internal transfer opportunity", 0),
    ("Promotion congratulations", 0),
    ("Performance review scheduled", 0),
    ("Feedback from manager", 0),
    ("Goals for next quarter", 0),
    ("Training opportunity available", 0),
    ("Conference registration open", 0),
    ("Scholarship opportunity", 0),
    ("Certification program details", 0),
    ("Professional development funds", 0),
    ("Tuition reimbursement available", 0),
    ("Mentorship program details", 0),
    ("Leadership development offered", 0),
    ("Team building event", 0),
    ("Social gathering this Friday", 0),
    ("Happy hour after work", 0),
    ("Dinner celebration for milestone", 0),
    ("Coffee with colleagues", 0),
    ("Lunch break plans", 0),
    ("Break room snacks available", 0),
    ("Kitchen facilities information", 0),
    ("Parking information", 0),
    ("Transportation options", 0),
    ("Shuttle schedule updated", 0),
    ("Commute assistance program", 0),
    ("Work from home policy", 0),
    ("Remote work options", 0),
    ("Office reopening date", 0),
    ("Desk assignment changed", 0),
    ("Facility upgrade information", 0),
    ("Building renovation schedule", 0),
    ("Security badge renewal", 0),
    ("Access card update", 0),
    ("Building emergency procedures", 0),
    ("Fire drill scheduled", 0),
    ("Safety training required", 0),
    ("Incident report filed", 0),
    ("Accident insurance claim", 0),
    ("Workers compensation information", 0),
    ("Sick leave policy", 0),
    ("Vacation time approved", 0),
    ("Holiday schedule announced", 0),
    ("Day off request approved", 0),
    ("Schedule change notification", 0),
    ("Shift assignment updated", 0),
    ("Coverage for absence", 0),
    ("Substitute worker details", 0),
    ("Temporary assignment info", 0),
    ("Contract renewal discussion", 0),
    ("Agreement terms approved", 0),
    ("Contract signed successfully", 0),
    ("Employment offer extended", 0),
    ("Start date confirmed", 0),
    ("Background check completed", 0),
    ("Reference check status", 0),
    ("Offer acceptance deadline", 0),
    ("Onboarding process begins", 0),
    ("First day orientation", 0),
    ("Equipment provision", 0),
    ("System access granted", 0),
    ("Account creation completed", 0),
    ("Email setup successful", 0),
    ("Software license assigned", 0),
    ("Tool access granted", 0),
    ("Resource allocation completed", 0),
    ("Team assignment confirmed", 0),
    ("Manager assignment", 0),
    ("Mentor assignment", 0),
    ("Buddy assignment", 0),
    ("Introduction email", 0),
    ("Welcome message", 0),
    ("Getting to know you", 0),
    ("Team introduction meeting", 0),
    ("Department overview", 0),
    ("Company culture overview", 0),
    ("Mission statement review", 0),
    ("Values discussion", 0),
    ("Strategic goals explained", 0),
    ("Vision for future", 0),
    ("Long term plans", 0),
    ("Growth opportunities", 0),
    ("Expansion plans announced", 0),
    ("New market entry", 0),
    ("Product launch announcement", 0),
    ("Feature release notes", 0),
    ("Software update available", 0),
    ("Patch release info", 0),
    ("Security update urgent", 0),
    ("Maintenance window notice", 0),
    ("System downtime scheduled", 0),
    ("Service interruption notice", 0),
    ("Data backup completed", 0),
    ("System migration info", 0),
    ("Database upgrade notice", 0),
    ("Infrastructure update", 0),
    ("Technology refresh", 0),
    ("Hardware replacement", 0),
    ("Equipment upgrade", 0),
    ("Software deployment", 0),
    ("Code release notes", 0),
    ("Bug fix details", 0),
    ("Performance improvement", 0),
    ("Security patch details", 0),
    ("Compliance update", 0),
    ("Privacy policy update", 0),
    ("Terms of service update", 0),
    ("Cookie policy notice", 0),
    ("Data protection notice", 0),
    ("GDPR compliance notice", 0),
    ("Data handling procedures", 0),
    ("Privacy practices", 0),
    ("Information security", 0),
    ("Cybersecurity alert", 0),
    ("Breach notification", 0),
    ("Phishing warning", 0),
    ("Password security reminder", 0),
    ("Two factor authentication", 0),
    ("Multi factor authentication", 0),
    ("Security best practices", 0),
    ("Verification methods", 0),
    ("Identity confirmation", 0),
    ("Account verification", 0),
    ("Email confirmation", 0),
    ("Phone verification", 0),
    ("SMS confirmation code", 0),
    ("Authentication code", 0),
    ("Verification link", 0),
    ("Confirmation required", 0),
    ("Action confirmation", 0),
    ("Request confirmation", 0),
    ("Approval notification", 0),
    ("Request status update", 0),
    ("Application status", 0),
    ("Processing update", 0),
    ("Pending decision", 0),
    ("Under review status", 0),
    ("Ready for review", 0),
    ("Awaiting approval", 0),
    ("Approved notification", 0),
    ("Rejection notice", 0),
    ("Appeal process", 0),
    ("Resubmission instructions", 0),
    ("Revision needed", 0),
    ("Comments on submission", 0),
    ("Feedback for improvement", 0),
    ("Suggestions for change", 0),
]

def train_model():
    texts = [item[0] for item in TRAINING_DATA]
    labels = [item[1] for item in TRAINING_DATA]
    
    vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=500)
    X = vectorizer.fit_transform(texts)
    
    X_train, X_test, y_train, y_test = train_test_split(
        X, labels, test_size=0.2, random_state=42
    )
    
    model = LogisticRegression(max_iter=200, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    print("\n" + "="*60)
    print("ML MODEL TRAINED")
    print("="*60)
    print(f"Precision: {precision_score(y_test, y_pred):.3f}")
    print(f"Recall:    {recall_score(y_test, y_pred):.3f}")
    print(f"F1-Score:  {f1_score(y_test, y_pred):.3f}")
    print("="*60 + "\n")
    
    return model, vectorizer

def ml_predict(text: str, model, vectorizer) -> int:
    vec = vectorizer.transform([text])
    return int(model.predict(vec)[0])